# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2101b244f477b6e57f0635d6f8a1f721"
name = "custom-signup-app"
handle = "custom-signup-app"
application_url = "https://shop-east-demands-chick.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products"

[auth]
redirect_urls = ["https://shop-east-demands-chick.trycloudflare.com/auth/callback", "https://shop-east-demands-chick.trycloudflare.com/auth/shopify/callback", "https://shop-east-demands-chick.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://shop-east-demands-chick.trycloudflare.com/api"
subpath = "custom-signup"
prefix = "apps"

[pos]
embedded = false
